app:
    storage_raw_path: storage/raw
    storage_images_path: storage/images
    storage_thumbs_path: storage/thumbs

    albums:
        stalker:
            title: Stalker Photo
            description: Inspiracją do stworzenia tego albumu była książka braci Strugackich pt. Piknik na skraju drogi. To właśnie do tej książki odsyłam cię jeśli chcesz dowiedzieć się kim są stalkerzy i czym się zajmują.
            pagination_limit: 3
            feed_limit: 10
            feed_url: http://feeds.feedburner.com/stalkerphoto

            # normal
            image_horizontal_max_width: 1500
            image_vertical_max_height: 0

            # thumb
            thumb_horizontal_max_width: 1500
            thumb_vertical_max_height: 0

            # IPTC tags
            tags:
                author: Rafal Toborek
                copyright: Rafal Toborek
                description: https://pstryk.toborek.info
