app:
    storage_raw_path: storage/raw
    storage_images_path: storage/images
    storage_thumbs_path: storage/thumbs

    albums:
        pstryk:
            title: Galeria pewnego pstryka
            description: Nie ma co gadać, tutaj Rafał pstryka.
            pagination_limit: 3
            feed_limit: 10
            feed_url: http://feeds.feedburner.com/RafalPstryka

            domains:
                - pstryk.toborek.info
                - pstryk.lh
                - localhost # to support functional tests only

            image_horizontal_max_width: 1600
            image_vertical_max_height: 1200

            thumb_horizontal_max_width: 1300
            thumb_vertical_max_height: 1000

            tags:
                author: Rafal Toborek
                copyright: Rafal Toborek
                description: https://pstryk.toborek.info

            watermark:
                enabled: true
                file: pstryk.png
                width: 180
                height: 51
                transparency: 100
                position: bottom-right
                horizontal_margin: 10
                vertical_margin: 10

        stalker:
            title: Stalker Photo
            description: Inspiracją do stworzenia tego albumu była książka braci Strugackich pt. Piknik na skraju drogi. To właśnie do tej książki odsyłam cię jeśli chcesz dowiedzieć się kim są stalkerzy i czym się zajmują.
            pagination_limit: 3
            feed_limit: 10
            feed_url: http://feeds.feedburner.com/stalkerphoto

            domains:
                - stalker.toborek.info
                - stalker.lh

            image_horizontal_max_width: 1600
            image_vertical_max_height: 1200

            thumb_horizontal_max_width: 1300
            thumb_vertical_max_height: 1000

            tags:
                author: Rafal Toborek
                copyright: Rafal Toborek
                description: https://stalker.toborek.info

            watermark:
                enabled: true
                file: stalker.png
                width: 180
                height: 100
                transparency: 60
                position: bottom-right
                horizontal_margin: 10
                vertical_margin: 10

        tysia:
            title: Tysia
            description: Album Zuzi.
            pagination_limit: 5
            feed_limit: 10

            domains:
                - tysia.toborek.info
                - tysia.lh

            image_horizontal_max_width: 1600
            image_vertical_max_height: 1600

            thumb_horizontal_max_width: 1300
            thumb_vertical_max_height: 1300

            tags:
                author: Rafal Toborek
                copyright: Rafal Toborek
                description: https://pstryk.toborek.info

            watermark:
                enabled: true
                file: tysia.png
                width: 130
                height: 101
                transparency: 100
                position: bottom-right
                horizontal_margin: 20
                vertical_margin: 20
