app:
    storage_raw_path: storage/raw
    storage_images_path: storage/images
    storage_thumbs_path: storage/thumbs

    albums:
        stalker:
            title: Stalker
            pagination_limit: 1000
            feed_limit: 10

            # normal
            image_horizontal_max_width: 0
            image_horizontal_max_height: 0
            image_vertical_max_width: 0
            image_vertical_max_height: 0

            # thumbs
            thumb_horizontal_max_width: 0
            thumb_horizontal_max_height: 0
            thumb_vertical_max_width: 0
            thumb_vertical_max_height: 0
