app:
    storage_raw_path: storage/raw
    storage_images_path: storage/images
    storage_thumbs_path: storage/thumbs

    albums:
        stalker:
            title: Stalker Photo
            description: Inspiracją do stworzenia tego albumu była książka braci Strugackich pt. Piknik na skraju drogi. To właśnie do tej książki odsyłam cię jeśli chcesz dowiedzieć się kim są stalkerzy i czym się zajmują.
            pagination_limit: 3
            feed_limit: 10
            feed_url: http://feeds.feedburner.com/stalkerphoto

            # supported domains
            domains:
                - stalker.toborek.info
                - stalker.lh

            # normal
            image_horizontal_max_width: 1600
            image_vertical_max_height: 0

            # thumb
            thumb_horizontal_max_width: 1300
            thumb_vertical_max_height: 0

            # IPTC tags
            tags:
                author: Rafal Toborek
                copyright: Rafal Toborek
                description: https://pstryk.toborek.info

            watermark:
                enabled: true
                file: watermark.png
                width: 120
                height: 120
                transparency: 60
                position: bottom-right
                horizontal_margin: 0
                vertical_margin: 0
